{"name": "Login con credenciales incorrectas -- @1.1 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643966054858, "stop": 1643966057083}, {"name": "When se lanza el login con \"badUser\" y \"secret_sauce\"", "status": "passed", "start": 1643966057083, "stop": 1643966057295}, {"name": "Then aparece la clase \"error\" en pantalla", "status": "passed", "attachments": [{"name": ".text", "source": "94647087-fac3-425f-b556-d8443de44007-attachment.txt", "type": "text/plain"}], "start": 1643966057296, "stop": 1643966057333}], "parameters": [{"name": "usuario", "value": "badUser"}, {"name": "contrasena", "value": "secret_sauce"}, {"name": "elemento", "value": "error"}], "start": 1643966054857, "stop": 1643966057387, "uuid": "ee5b383e-e79d-4b0f-8b50-57f285b98e1b", "historyId": "927c8a39cb7604db2d853930dde257ab", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}