{"name": "Login con credenciales incorrectas -- @1.2 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925970136, "stop": 1643925972695}, {"name": "When se lanza el login con \"standard_user\" y \"badPass\"", "status": "passed", "start": 1643925972696, "stop": 1643925973009}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "attachments": [{"name": ".text", "source": "aaa05908-6a4e-4d8f-805f-a9df5dde6bf4-attachment.txt", "type": "text/plain"}], "start": 1643925973010, "stop": 1643925973071}], "parameters": [{"name": "usuario", "value": "standard_user"}, {"name": "contrasena", "value": "badPass"}, {"name": "elemento", "value": "error"}], "start": 1643925970134, "stop": 1643925973184, "uuid": "2beda3ce-aecd-41db-877c-43d790fdaa01", "historyId": "18c2b466ba1027e8b508183464531113", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}