{"name": "Login con credenciales incorrectas -- @1.6 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925635567, "stop": 1643925638125}, {"name": "When se lanza el login con \"badUse3r\" y \"bad4Pass\"", "status": "passed", "start": 1643925638125, "stop": 1643925638438}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "start": 1643925638438, "stop": 1643925638496}], "parameters": [{"name": "usuario", "value": "badUse3r"}, {"name": "contrasena", "value": "bad4Pass"}, {"name": "elemento", "value": "error"}], "start": 1643925635566, "stop": 1643925638553, "uuid": "69442204-349f-42af-b0a5-f108b2347cff", "historyId": "a8c8871d450988a58661e683ac6d36d9", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}