{"name": "Login con credenciales incorrectas -- @1.2 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643966057389, "stop": 1643966059507}, {"name": "When se lanza el login con \"standard_user\" y \"badPass\"", "status": "passed", "start": 1643966059507, "stop": 1643966059745}, {"name": "Then aparece la clase \"error\" en pantalla", "status": "passed", "attachments": [{"name": ".text", "source": "1ea19875-7177-4629-9ff9-da6749e9342b-attachment.txt", "type": "text/plain"}], "start": 1643966059745, "stop": 1643966059762}], "parameters": [{"name": "usuario", "value": "standard_user"}, {"name": "contrasena", "value": "badPass"}, {"name": "elemento", "value": "error"}], "start": 1643966057388, "stop": 1643966059816, "uuid": "bcdff258-e4d5-476c-b343-bdda27ba8f58", "historyId": "18c2b466ba1027e8b508183464531113", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}