{"name": "Login con credenciales incorrectas -- @1.1 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643928527637, "stop": 1643928530235}, {"name": "When se lanza el login con \"badUser\" y \"secret_sauce\"", "status": "passed", "start": 1643928530236, "stop": 1643928530599}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "attachments": [{"name": ".text", "source": "698eb5b1-a204-4d0f-9742-6e8a45764039-attachment.txt", "type": "text/plain"}], "start": 1643928530600, "stop": 1643928530625}], "parameters": [{"name": "usuario", "value": "badUser"}, {"name": "contrasena", "value": "secret_sauce"}, {"name": "elemento", "value": "error"}], "start": 1643928527636, "stop": 1643928530682, "uuid": "3fd89151-3f0b-4071-be4c-ddf477a4fbf6", "historyId": "927c8a39cb7604db2d853930dde257ab", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}