{"name": "Login con credenciales incorrectas -- @1.2 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643928530684, "stop": 1643928533154}, {"name": "When se lanza el login con \"standard_user\" y \"badPass\"", "status": "passed", "start": 1643928533154, "stop": 1643928533483}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "attachments": [{"name": ".text", "source": "31848d78-9238-439a-84a7-9c107917e1f1-attachment.txt", "type": "text/plain"}], "start": 1643928533483, "stop": 1643928533544}], "parameters": [{"name": "usuario", "value": "standard_user"}, {"name": "contrasena", "value": "badPass"}, {"name": "elemento", "value": "error"}], "start": 1643928530683, "stop": 1643928533600, "uuid": "5fc8433b-8ac1-480d-b391-b68fdffadbe4", "historyId": "18c2b466ba1027e8b508183464531113", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}