{"name": "Login con credenciales incorrectas -- @1.5 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925632673, "stop": 1643925635142}, {"name": "When se lanza el login con \"badUser 4\" y \"bad4Pass\"", "status": "passed", "start": 1643925635143, "stop": 1643925635451}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "start": 1643925635451, "stop": 1643925635507}], "parameters": [{"name": "usuario", "value": "badUser 4"}, {"name": "contrasena", "value": "bad4Pass"}, {"name": "elemento", "value": "error"}], "start": 1643925632672, "stop": 1643925635564, "uuid": "f2a6c9af-4cbb-46b2-9445-6116c8d0936d", "historyId": "7f2b8e02ee2ff768fde92c3a9ccb3749", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}