{"name": "Login con credenciales incorrectas -- @1.4 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925629808, "stop": 1643925632249}, {"name": "When se lanza el login con \"badUse3r\" y \"badPa4ss\"", "status": "passed", "start": 1643925632250, "stop": 1643925632590}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "start": 1643925632590, "stop": 1643925632614}], "parameters": [{"name": "usuario", "value": "badUse3r"}, {"name": "contrasena", "value": "badPa4ss"}, {"name": "elemento", "value": "error"}], "start": 1643925629807, "stop": 1643925632670, "uuid": "d11b96ac-e07f-4311-b627-a33e0f91b451", "historyId": "3728b7cff4512ff1efafaf89e41b159b", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}