{"name": "Login con credenciales incorrectas -- @1.1 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925965987, "stop": 1643925969652}, {"name": "When se lanza el login con \"badUser\" y \"secret_sauce\"", "status": "passed", "start": 1643925969653, "stop": 1643925970044}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "attachments": [{"name": ".text", "source": "9ec44082-5e51-49bf-81b3-1e8dbfd7c6ca-attachment.txt", "type": "text/plain"}], "start": 1643925970045, "stop": 1643925970070}], "parameters": [{"name": "usuario", "value": "badUser"}, {"name": "contrasena", "value": "secret_sauce"}, {"name": "elemento", "value": "error"}], "start": 1643925965986, "stop": 1643925970130, "uuid": "b1396169-3c76-4f47-9336-59f5afc34582", "historyId": "927c8a39cb7604db2d853930dde257ab", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}