{"name": "Login con credenciales incorrectas -- @1.3 ", "status": "passed", "steps": [{"name": "Given se ha inicializado el contexto", "status": "passed", "start": 1643925626880, "stop": 1643925629391}, {"name": "When se lanza el login con \"badUse2r\" y \"bad44Pass\"", "status": "passed", "start": 1643925629392, "stop": 1643925629724}, {"name": "Then aparece \"error\" en pantalla", "status": "passed", "start": 1643925629724, "stop": 1643925629749}], "parameters": [{"name": "usuario", "value": "badUse2r"}, {"name": "contrasena", "value": "bad44Pass"}, {"name": "elemento", "value": "error"}], "start": 1643925626879, "stop": 1643925629805, "uuid": "b76e9a09-d227-4c8e-83ea-aac7372a02fc", "historyId": "c335cbb3d2fa17bfc136e907854f5913", "fullName": "Pruebas sobre el login: Login con credenciales incorrectas", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Pruebas sobre el login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}